server:
  port: 9201
spring:
  profiles:
    active: dev
  application:
    name: oauth-gateway
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql:///wlliu_blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes: #配置路由路径
        - id: oauth-api-route
          uri: lb://oauth-api
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: oauth-auth-route
          uri: lb://oauth-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    port: 6379
    host: 47.100.202.70
mybatis-plus:
  type-aliases-package: com.wlliu.domain
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/**"
      - "/login"
      #- "/**"